# Generated by Django 3.0.9 on 2020-08-05 14:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 5, 14, 46, 27, 94117, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
